name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry 
          poetry install
      
      - name: Format with ruff
        run: |
          poetry run ruff format .
          
      - name: Sort imports with isort
        run: |
          poetry run isort .
      
      - name: Commit changes if any
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Apply auto-formatting changes" && git push)
        # Only run on push to main, not on PRs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      
      - name: Lint with pyright
        run: |
          poetry run pyright .
      
      - name: Type check with mypy
        run: |
          poetry run mypy .

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: | 
          poetry run nox
